apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: workshop-springboot-using_camel
  title: Event-Driven Integration with Camel & Spring Boot
  description: |
    Event-Driven Microservices with Camel & Spring Boot
  annotations:
    backstage.io/techdocs-ref: dir:.
#   backstage.io/techdocs-ref: dir:https://<hosted-git-repo>   # use absolute path instead to consolidate techdocs among repo forks
#   gitlab.com/instance: ""                                    # uncomment these two gitlab.com lines to disable GitLab tabs
#   gitlab.com/project-slug: ""                                # i.e. Issues, Pull/Merge Requests, CI in entity details
  tags:
    - camel
    - springboot
# links:
#   - url: https://<devspaces-url>/#<hosted-git-repo>
#     title: 🚀 Launch from Dev Spaces
#     icon: web
spec:
  type: module
  lifecycle: development
  owner: user:default/workshop-admins
  subcomponentOf: component:default/workshop-repository
