site_name: Event-Driven Microservices
site_description: Event-Driven Microservices with Camel & Spring Boot

nav:
  - Overview: index.md
  - Spring Boot: springboot.md
  - Minio: minio.md
  - Links: links.md

plugins:
  - techdocs-core
