#----------------------------------
# Camel REST
#----------------------------------
camel.rest.component=platform-http

#----------------------------------
# Kafka
#----------------------------------
camel.component.kafka.brokers=kafka-kafka-bootstrap:9092

# PLACE TOPIC NAMES HERE
# ----------------------------------------
# Input topic
kafka.package.receiver=package-receiver
# Output topic
kafka.package.deliverer=package-deliverer
# ----------------------------------------

#----------------------------------
# MinIO
#----------------------------------
minio.bucket=camel-drop
minio.accessKey=admin
minio.secretKey=admin123
minio.endpoint=http://minio:9000
